name: Wake Streamlit App

on:
  schedule: # Triggers 4 hours automatically for 12 hours limit
   - cron: "0 */4 * * *"
  workflow_dispatch: # Allows manual trigger via UI if needed 

jobs:
  wake_app:
    run-on: ubuntu-latest
    steps:
      - name: Send Lightweight Ping
        run: curl -I https://streamlit.app
  
